import { cn } from "@/lib/utils";

/**
 * App logo — renders the generated maskable icon at a fixed size with the
 * iOS-style squircle masked via CSS so the shadow + outline hug the visible
 * shape. Use this anywhere we'd otherwise drop a coloured Fish-icon box.
 *
 * Source images are generated by `npm run generate:icons` from
 * /public/logo-source.png and live in /public/icons/.
 */
export function Logo({
  size = "md",
  className,
  shadow = true,
}: {
  size?: "xs" | "sm" | "md" | "lg" | "xl";
  className?: string;
  shadow?: boolean;
}) {
  const dimension = {
    xs: "w-6 h-6 rounded-md",
    sm: "w-7 h-7 rounded-lg",
    md: "w-9 h-9 rounded-xl",
    lg: "w-12 h-12 rounded-2xl",
    xl: "w-16 h-16 rounded-[1.25rem]",
  }[size];

  return (
    <img
      src="/icons/icon-192-maskable.png"
      alt="SardineWatch logo"
      width={192}
      height={192}
      className={cn(
        dimension,
        shadow && "shadow-lg shadow-ocean-500/30",
        className
      )}
    />
  );
}
